# Pandas

In [3]:
# def: pandas is open source python library used for the data manipulation and analysis.
# Pandas is designed the NumPy library.

# installing and importing pandas

In [6]:
# pip install pandas

import pandas as pd

In [8]:
pd.__version__

'2.2.2'

## Data Structure in Pandas (DataFrame, Series)

In [11]:
# series : 1D array
# DataFrame :  2D array

# Series Data Structure

In [14]:
# Series is a 1D Homogeneous array.

In [16]:
ser1 = pd.Series()  #empty series
print(ser1)
print(type(ser1))

Series([], dtype: object)
<class 'pandas.core.series.Series'>

In [18]:
ser2 = pd.Series(["abc",10,20,30,40,50])
print(ser2)
print(type(ser2))

# strings in pandas are retpresented as "object".
#internally, pandas convert all the elements to string if even a single element passed is string

0    abc
1     10
2     20
3     30
4     40
5     50
dtype: object
<class 'pandas.core.series.Series'>

In [20]:
ser3 = pd.Series(["Python","Machine_learning","Deep_learning","Generative AI"])
print(ser3)

0              Python
1    Machine_learning
2       Deep_learning
3       Generative AI
dtype: object

In [22]:
# pandas series don't support negative indexing
ser3[1]
#ser3[-1]

'Machine_learning'

# DataFrame : 2D array

In [25]:
df1 = pd.DataFrame()
print(df1)

Empty DataFrame
Columns: []
Index: []

In [27]:
df2 = pd.DataFrame([["AI",100,20],["ML",200,10],["DL",300,40],["NLP",400,50]], columns = ["Subjects","Price","No.Of students"])
print(df2)

  Subjects  Price  No.Of students
0       AI    100              20
1       ML    200              10
2       DL    300              40
3      NLP    400              50

In [29]:
df2 = pd.DataFrame([("AI",100,20),("ML",200,10),("DL",300,40),("NLP",400,50)], columns = ["Subjects","Price","No.Of students"])
print(df2)

  Subjects  Price  No.Of students
0       AI    100              20
1       ML    200              10
2       DL    300              40
3      NLP    400              50

In [31]:
# Convert dictionary to dataFrame.

fav_hero ={
    "Hero_name" : ["GopiChand","Pavan Kalyan","Allu Arjun","Ram Charan"],
    "Fees" : [30,00,100,50]
}

df4 = pd.DataFrame(fav_hero)
df4

      Hero_name  Fees
0     GopiChand    30
1  Pavan Kalyan     0
2    Allu Arjun   100
3    Ram Charan    50

# importing data from different files into DataFrame

In [34]:
import os
os.getcwd()

'C:\\Users\\Bandla\\Documents\\codegyan\\Python-Practice'

In [36]:
df_csv = pd.read_csv("csv_data.csv")
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [38]:
df = pd.read_excel("Excel_data")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

# Loading data from SQL/JSON file

In [39]:
# Explore the data from dataframe to csv & Excel file

df.to_csv("ds20_csv.csv")
df.to_excel("ds20_excel.xlsx")

In [42]:
import pandas as pd
import sqlite3

In [48]:
# created empty database connection
conn = sqlite3.connect("Ds20_database.db")

In [50]:
import os 
os.getcwd()

'C:\\Users\\Bandla\\Documents\\codegyan\\Python-Practice'

In [53]:
df = pd.read_excel("Excel_data")
df.to_sql("table1",conn, if_exists = "replace")

500

In [59]:
df1 = pd.read_sql("select * from table1",conn)
df1

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

# Loading/storing data from JSON

In [62]:
df2 = pd.read_json("json_data.json")
df2

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

# understand the dataset using pandas

In [75]:
df = pd.read_excel("Excel_data")

In [79]:
#
df.shape

(500, 6)

In [73]:
df.head(10)

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1
5   4      Rocky  56.0         Chef  117920                        3
6   4      Rocky  56.0         Chef  117920                       11
7   4      Rocky  56.0         Chef  117920                        2
8   4      Rocky  56.0         Chef  117920                        2
9   4      Rocky  56.0         Chef  117920                        3

In [81]:
df.tail(5)

      ID      Name   Age         Profession  salary  Marriage_proposal_count
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [83]:
# Query: Name column only
df.Name

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [85]:
df["Age"]

0      23.0
1      20.0
2      38.0
3      56.0
4      56.0
       ...
495    45.0
496    46.0
497    47.0
498    55.0
499    59.0
Name: Age, Length: 500, dtype: float64

In [99]:
# Print Multiple columns (Age & Salary)

df[["Age","salary","Profession","Marriage_proposal_count"]]

      Age  salary         Profession  Marriage_proposal_count
0    23.0  184518            Teacher                        0
1    20.0  119572              Boxer                        2
2    38.0  174897          Scientist                        1
3    56.0  117920               Chef                        2
4    56.0  117920               Chef                        1
..    ...     ...                ...                      ...
495  45.0  137929              Boxer                        0
496  46.0   39870              Boxer                        6
497  47.0  165951          Detective                        5
498  55.0  192618           Comedian                        5
499  59.0  194886  Software Engineer                       28

[500 rows x 4 columns]

In [101]:
# rename the columns

df2 = df.rename(columns = {"Name" : "Peru","Age":"Vayasu","Profession":"Vruti"})
df2

,ID,Peru,Vayasu,Vruti,salary,Marriage_proposal_count
0,1,olivia,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,56.0,Chef,117920,2
4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,55.0,Comedian,192618,5
499,500,Sherlock,59.0,Software Engineer,194886,28

In [107]:
# Add a new column in dataset
# rank() function provide the rank based upon the salary
# lower salary = lower rank



df["rank"] = df.salary.rank(ascending = False)
df.sort_values("rank")

#if column already present then this will update the column.
#if column don't exist then new column will be created.

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank
436,437,Sherlock,52.0,Boxer,199529,3,1.0
65,66,Emma,57.0,Pilot,199317,1,2.0
132,133,Rocky,31.0,Doctor,198978,8,3.0
167,168,Mr. Bean,44.0,Comedian,198847,14,4.0
474,475,Sophia,30.0,Doctor,198653,1,5.0
...,...,...,...,...,...,...,...
284,285,Jake,46.0,Detective,30971,1,496.0
329,330,Sherlock,40.0,Scientist,30905,0,497.0
398,399,Rocky,25.0,Scientist,30659,5,498.0
90,91,Rocky,43.0,Software Engineer,30407,10,499.0
213,214,Sherlock,21.0,Chef,30164,2,500.0

# drop a column from dataframe

In [114]:
df = df.drop(["rank"],axis = 1)
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

# Replace the Value in DataFrame

In [ ]:
df.Name = df.Name.reeplace({})

In [119]:
# all the columns datatypes

df.dtypes

ID                           int64
Name                        object
Age                        float64
Profession                  object
salary                       int64
Marriage_proposal_count      int64
dtype: object

In [126]:
# convert one data type to another

df.Name = df.salary.astype('float')
df.dtypes

ID                           int64
Name                       float64
Age                        float64
Profession                  object
salary                       int64
Marriage_proposal_count      int64
dtype: object

In [128]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [130]:
# print only categorical column names

df.select_dtypes(include = ["object","string"]).columns

Index(['Profession'], dtype='object')

In [132]:
df.select_dtypes(include = ["int","float"]).columns

Index(['ID', 'Name', 'Age', 'salary', 'Marriage_proposal_count'], dtype='object')

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    float64
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   salary                   500 non-null    int64
 5   Marriage_proposal_count  500 non-null    int64
dtypes: float64(2), int64(3), object(1)
memory usage: 23.6+ KB

In [138]:
df.Profession.unique()

array(['Teacher', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [140]:
# printing unique profession
df.Marriage_proposal_count.value_counts()

Marriage_proposal_count
2     81
0     76
1     75
4     68
3     66
5     59
14     8
8      8
12     7
13     7
15     7
6      6
7      6
10     6
9      5
11     5
26     1
21     1
30     1
38     1
34     1
32     1
37     1
40     1
31     1
28     1
Name: count, dtype: int64

In [142]:
# count number of people in each profession

df.Marriage_proposal_count.unique()

array([ 0,  2,  1,  3, 11,  5, 12, 13,  4,  8,  7, 10, 21,  9, 14, 26, 15,
       30,  6, 38, 34, 32, 37, 40, 31, 28], dtype=int64)

In [144]:
df.groupby("Profession").Marriage_proposal_count.sum()

Profession
      Boxer          216
Artist               138
Chef                 239
Comedian             306
Detective            219
Doctor               161
Pilot                174
Scientist            185
Software Engineer    217
Teacher              158
Name: Marriage_proposal_count, dtype: int64

In [51]:
import pandas as pd

df = pd.read_excel("Excel_data")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [53]:
df.Profession.unique()

array(['Teacher', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [55]:
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

In [57]:
# describe() function is used for statstical information
df.describe()

               ID         Age         salary  Marriage_proposal_count
count  500.000000  492.000000     500.000000                500.00000
mean   250.458000   40.810976  115602.828000                  4.02600
std    144.552978   11.790553   49404.366846                  5.25362
min      1.000000   20.000000   30164.000000                  0.00000
25%    125.750000   31.000000   74964.750000                  1.00000
50%    250.500000   40.500000  117920.000000                  3.00000
75%    375.250000   51.000000  160579.500000                  5.00000
max    500.000000   60.000000  199529.000000                 40.00000

In [59]:
# count = number of null-value
# mean = average 
# std = standard deviation : how much data is far away from mean
# percentage or percentile

# percentile:from how many people i am ahead

In [61]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [63]:
df.dtypes

ID                           int64
Name                        object
Age                        float64
Profession                  object
salary                       int64
Marriage_proposal_count      int64
dtype: object

In [65]:
df.describe(include = "object")

            Name Profession
count        500        500
unique        13         10
top     Sherlock       Chef
freq          61         58

In [67]:
df.Name.unique()

array(['olivia', 'sophia   ', 'jake', 'Rocky', 'Jake', 'Olivia', 'John',
       'Sherlock', 'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'],
      dtype=object)

In [69]:
df.Name.value_counts()

Name
Sherlock     61
Emma         57
John         55
Alice        53
Mr. Bean     52
Olivia       50
Jake         47
Rocky        44
Sophia       41
Liam         37
olivia        1
sophia        1
jake          1
Name: count, dtype: int64

# Data filtering and indexing

In [72]:
df.salary > 100000

0       True
1       True
2       True
3       True
4       True
       ...
495     True
496    False
497     True
498     True
499     True
Name: salary, Length: 500, dtype: bool

In [74]:
# Query: find those records where salary >  10000

df[df.salary > 100000]

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
493  494     Sophia  39.0             Doctor  174500                        0
495  496       John  45.0              Boxer  137929                        0
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[304 rows x 6 columns]

In [76]:
df[df.salary < 50000]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
13    14      John  46.0             Artist   43078                       12
39    40    Olivia  60.0  Software Engineer   32286                        1
40    41     Alice  52.0               Chef   46535                        4
41    42     Rocky  39.0             Doctor   39660                        7
49    50      Liam  59.0              Pilot   37285                       21
..   ...       ...   ...                ...     ...                      ...
447  448  Mr. Bean  59.0             Doctor   37507                       15
462  463    Sophia  32.0          Detective   31851                        3
489  490      John  56.0          Scientist   41192                        7
494  495     Rocky  27.0             Doctor   46975                        0
496  497  Sherlock  46.0              Boxer   39870                        6

[64 rows x 6 columns]

In [78]:
# Query: find those records where salary > 50000 & salary < 10000
df[(df.salary > 50000) & (df.salary > 15000)].shape

(436, 6)

In [80]:
# Query: Find the record of the person who get the maximum salary.

df[df.salary == df.salary.max()]

      ID      Name   Age   Profession  salary  Marriage_proposal_count
436  437  Sherlock  52.0        Boxer  199529                        3

In [82]:
# find the record of the person who got max.marriage proposals

df[df.Marriage_proposal_count == df.Marriage_proposal_count.max()]

      ID   Name   Age Profession  salary  Marriage_proposal_count
399  400  Rocky  52.0   Comedian   69267                       40

# indexing

In [85]:
# loc and iloc

In [87]:
# Query: Print 1 to 6 records and name to profession columns

In [89]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [93]:
#df.Loc[row,col]
df.loc[1:6,"Name" : "Profession"]

        Name   Age   Profession
1  sophia     20.0        Boxer
2       jake  38.0    Scientist
3      Rocky  56.0         Chef
4      Rocky  56.0         Chef
5      Rocky  56.0         Chef
6      Rocky  56.0         Chef

In [103]:
df.loc[10:20,["Age","salary"]]

     Age  salary
10   NaN   75543
11   NaN  174780
12  22.0  102063
13  46.0   43078
14  40.0  171553
15  30.0   57774
16  46.0  135907
17  53.0  127117
18  25.0  181312
19  40.0  118998
20  40.0  118998

# iloc

In [106]:
# Query: print record from 1 to 6 and columns from 1 to 3

In [108]:
df.iloc[1:7, 1:4]

        Name   Age   Profession
1  sophia     20.0        Boxer
2       jake  38.0    Scientist
3      Rocky  56.0         Chef
4      Rocky  56.0         Chef
5      Rocky  56.0         Chef
6      Rocky  56.0         Chef

In [ ]:
# interview Question : what is the difference between the loc and iloc?
#Ans: in loc, we need to mention the columns names , but in iloc we mention the index of the particular columns index values.

#iloc goes upto n-1 , but loc goes upto nth value.
# iloc is little faster than loc.
# beacause loc need to convert columns names to index.

In [110]:
df.iloc[0,2]

23.0

In [112]:
df.iloc[0,1]

'olivia'

In [114]:
df.at[0,"Name"]

'olivia'

In [116]:
df.iat[0,1]

'olivia'

In [118]:
# at & iat are used specifically to access single element
# at & iat faster than loc & iloc

# Handling Null values

In [2]:
import pandas as pd
df = pd.read_excel("excel_data")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [4]:
# Null : the information which is not provided
# NaN , na : 

#Null vs 0

# o is a value, while  null means no value available

In [6]:
# identify the null valuesin dataFrames

df.isnull().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [8]:
df.isna().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [12]:
# find the null value in a specific columns

df.Age.isnull().sum()

8

In [18]:
# print the records with null values

df[df.Age.isnull()]

    ID      Name  Age         Profession  salary  Marriage_proposal_count
10  11     Rocky  NaN             Doctor   75543                        5
11  12      Jake  NaN             Artist  174780                        5
45  46      Liam  NaN             Doctor   84583                        0
46  47  Mr. Bean  NaN             Artist  190559                        5
71  72      Emma  NaN              Pilot   49986                        3
72  73    Sophia  NaN             Artist   86741                        1
73  74     Rocky  NaN  Software Engineer  159260                        0
74  75  Sherlock  NaN          Detective  165463                        0

In [20]:
df[df.Age.isna()]

    ID      Name  Age         Profession  salary  Marriage_proposal_count
10  11     Rocky  NaN             Doctor   75543                        5
11  12      Jake  NaN             Artist  174780                        5
45  46      Liam  NaN             Doctor   84583                        0
46  47  Mr. Bean  NaN             Artist  190559                        5
71  72      Emma  NaN              Pilot   49986                        3
72  73    Sophia  NaN             Artist   86741                        1
73  74     Rocky  NaN  Software Engineer  159260                        0
74  75  Sherlock  NaN          Detective  165463                        0

In [28]:
# delete the records which is having null values
df1 = df.copy()
df1.dropna(inplace = True)

In [30]:
df1.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [32]:
df1.shape

(492, 6)

In [34]:
# why we need to handle the null values
Ans: in-built function might not work propoerly (numpy and python)
# Pandas function can work but will give the wrong answer as it will not include the NaN value
import numpy as np
vals = [10,20,30,40,np.nan]
np.mean(vals)

nan

In [36]:
df.Age.mean()

40.8109756097561

In [38]:
ser1 = pd.Series(vals)
ser1.mean()

25.0

In [50]:
# Approach-1 : delete the records which is having null values
# Approach-2 : delete the column which is having the null value


df2 = df.copy()
# axis = 1 : delete the column which is having null value
# axis = 0 : delete the column even that have single null value
# how = "any" : delete the column even that have single null value
# how = "all" : delete the column only if all the value in that column is Null

df2 = df2.dropna(axis = 1, how = "any")
df2.isnull().sum()

ID                         0
Name                       0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [52]:
# Approach-3 : replace the null value with some constant

df3 = df.copy()

In [54]:
# fillna() function is used to fill the null values with some other value

df3.Age = df3.Age.fillna(18)

In [56]:
df3.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [58]:
df3.shape

(500, 6)

In [60]:
avg_age = df.Age.mean()

In [64]:
df.Age = df.Age.fillna(avg_age)

In [66]:
df.Age.isnull().sum()

0

# Handling Duplicates Values

In [69]:
# show the duplcates records
# if a record is completely matching with same other record
df[df.duplicated()]

   ID   Name   Age Profession  salary  Marriage_proposal_count
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [71]:
# Keep = False : show both the records
df[df.duplicated(keep = False)]

   ID   Name   Age Profession  salary  Marriage_proposal_count
3   4  Rocky  56.0       Chef  117920                        2
5   4  Rocky  56.0       Chef  117920                        3
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

# keep = False : show both the  records
# Keep = first : Mark duplicates as True except for the first occurance
# '''last''' :  mark duplcates as ''True'' except for the last occurance

In [77]:
df[df.duplicated(keep = "first")]

   ID   Name   Age Profession  salary  Marriage_proposal_count
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [81]:
df[df.duplicated(keep = "last")]

   ID   Name   Age Profession  salary  Marriage_proposal_count
3   4  Rocky  56.0       Chef  117920                        2
5   4  Rocky  56.0       Chef  117920                        3
7   4  Rocky  56.0       Chef  117920                        2

# Handling inconsistent data

In [24]:
import pandas as pd
df = pd.read_excel("Excel_data")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [26]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [28]:
# Make the column name consistent
# make all the columns name start with capital letter

df.columns = df.columns.str.title()

In [30]:
df.columns

Index(['Id', 'Name', 'Age', 'Profession', 'Salary', 'Marriage_Proposal_Count'], dtype='object')

In [32]:
df.Name.unique()

array(['olivia', 'sophia   ', 'jake', 'Rocky', 'Jake', 'Olivia', 'John',
       'Sherlock', 'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'],
      dtype=object)

In [34]:
#str. strip() remove the extra space from front and trail
df.Name = df.Name.str.strip()

In [36]:
df.Name.unique()

array(['olivia', 'sophia', 'jake', 'Rocky', 'Jake', 'Olivia', 'John',
       'Sherlock', 'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'],
      dtype=object)

In [38]:
df.Profession.unique()

array(['Teacher', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [40]:
df.Profession = df.Profession.str.strip()

In [42]:
df.Profession.unique()

array(['Teacher', 'Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

# Data Transformation using apply() and map() function

# apply() : this function is used to execute lambda function

# lambda function is one line function

# if you want to apply lambda function on DataFrame then we use the apply() function.

In [47]:
df1 = df.copy()

In [49]:
# on the festival occation : Sai Ram decided top double the employee salary
df

      Id      Name   Age         Profession  Salary  Marriage_Proposal_Count
0      1    olivia  23.0            Teacher  184518                        0
1      2    sophia  20.0              Boxer  119572                        2
2      3      jake  38.0          Scientist  174897                        1
3      4     Rocky  56.0               Chef  117920                        2
4      4     Rocky  56.0               Chef  117920                        1
..   ...       ...   ...                ...     ...                      ...
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [53]:
# on the festival occation: Sai ram decided to double the emp. salary

df1.Salary = df1.Salary.apply(lambda x : x*2)
df1

      Id      Name   Age         Profession  Salary  Marriage_Proposal_Count
0      1    olivia  23.0            Teacher  738072                        0
1      2    sophia  20.0              Boxer  478288                        2
2      3      jake  38.0          Scientist  699588                        1
3      4     Rocky  56.0               Chef  471680                        2
4      4     Rocky  56.0               Chef  471680                        1
..   ...       ...   ...                ...     ...                      ...
495  496      John  45.0              Boxer  551716                        0
496  497  Sherlock  46.0              Boxer  159480                        6
497  498  Sherlock  47.0          Detective  663804                        5
498  499    Olivia  55.0           Comedian  770472                        5
499  500  Sherlock  59.0  Software Engineer  779544                       28

[500 rows x 6 columns]

In [55]:
# Create a new column :  Bonus or No-Bonus
df1["Diwali_gift"] = df1.apply(lambda row: "Bonus" if row["Salary"] < 100000 else "No_Bonus",axis = 1)

In [57]:
df1

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Diwali_gift
0,1,olivia,23.0,Teacher,738072,0,No_Bonus
1,2,sophia,20.0,Boxer,478288,2,No_Bonus
2,3,jake,38.0,Scientist,699588,1,No_Bonus
3,4,Rocky,56.0,Chef,471680,2,No_Bonus
4,4,Rocky,56.0,Chef,471680,1,No_Bonus
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,551716,0,No_Bonus
496,497,Sherlock,46.0,Boxer,159480,6,No_Bonus
497,498,Sherlock,47.0,Detective,663804,5,No_Bonus
498,499,Olivia,55.0,Comedian,770472,5,No_Bonus
499,500,Sherlock,59.0,Software Engineer,779544,28,No_Bonus

# Map() function:

In [60]:
# Map() : this function is used for element wise transformation

In [62]:
df.Profession.unique()

array(['Teacher', 'Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [72]:
map_dict = {
    "Teacher" : "Guruvu",
    "Boxer" : "Peddi",
    "Scientist" : "Sastravayakta",
    "Chef" : "Vantalaka",
    "Doctor" : "Vayadidu",
    "Artist" : "kalakarudu",
    "Comedian" : "HasyaNatudu",
    "Software Engineer" : "Coolie",
    "Detective" : "Gudachari",
    "Pilot" : "Gallilodu"
}

In [76]:
df1["Profession_new"]  = df1.Profession.map(map_dict)
df1

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Diwali_gift,Profession_new
0,1,olivia,23.0,Teacher,738072,0,No_Bonus,Guruvu
1,2,sophia,20.0,Boxer,478288,2,No_Bonus,Peddi
2,3,jake,38.0,Scientist,699588,1,No_Bonus,Sastravayakta
3,4,Rocky,56.0,Chef,471680,2,No_Bonus,Vantalaka
4,4,Rocky,56.0,Chef,471680,1,No_Bonus,Vantalaka
...,...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,551716,0,No_Bonus,Peddi
496,497,Sherlock,46.0,Boxer,159480,6,No_Bonus,Peddi
497,498,Sherlock,47.0,Detective,663804,5,No_Bonus,Gudachari
498,499,Olivia,55.0,Comedian,770472,5,No_Bonus,HasyaNatudu
499,500,Sherlock,59.0,Software Engineer,779544,28,No_Bonus,Coolie

# Aggregations and Grouping functions

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Id                       500 non-null    int64
 1   Name                     500 non-null    object
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   Salary                   500 non-null    int64
 5   Marriage_Proposal_Count  500 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 23.6+ KB

In [81]:
# sum the total salary

print(df.Salary.sum())

57801414

In [85]:
# average of salary
print(df.Salary.mean())

115602.828

In [ ]:
# Median : middle value after sorting the data
# even : sum middle values / 2

In [88]:
print(df.Salary.median())

117920.0

In [92]:
# Mode : most frequent value 
# mode works with categorical date or numerical data with repeted values

df.Profession.mode()

0    Chef
Name: Profession, dtype: object

In [94]:
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
Boxer                53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

In [96]:
# minimum.salary
df.Salary.min()

30164

In [98]:
# maximum salary
df.Salary.max()

199529

In [100]:
# variance : How much the data far away from mean

df.Salary.var()

2440791463.4653473

In [102]:
# standard deviation : how much the data far away from mean
df.Salary.std()

49404.366846113386

# difference between count and size

Size : total values of both nan and null values
count : only counts the NaN values

# Grouping of data

In [3]:
import pandas as pd
df = pd.read_excel("Excel_data")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [5]:
# group the data based upon the profession
df.groupby("Profession").count()

                   ID  Name  Age  salary  Marriage_proposal_count
Profession
      Boxer        53    53   53      53                       53
Artist             41    41   38      41                       41
Chef               58    58   58      58                       58
Comedian           52    52   52      52                       52
Detective          45    45   44      45                       45
Doctor             48    48   46      48                       48
Pilot              53    53   52      53                       53
Scientist          54    54   54      54                       54
Software Engineer  51    51   50      51                       51
Teacher            45    45   45      45                       45

In [7]:
# find the  average salary based upon the profession

df.groupby("Profession").salary.mean()

Profession
      Boxer          103895.867925
Artist               124550.756098
Chef                 110806.620690
Comedian             122689.000000
Detective            120964.977778
Doctor               113964.333333
Pilot                108641.471698
Scientist            126669.481481
Software Engineer    117908.941176
Teacher              107922.711111
Name: salary, dtype: float64

In [9]:
# group the data based upon multiple columns
df.groupby(["Profession","Age"]).salary.mean()

Profession   Age
      Boxer  20.0     77449.000000
             23.0     30976.000000
             25.0    132741.500000
             26.0    128217.000000
             27.0    139444.000000
                         ...
Teacher      56.0     51422.000000
             57.0     87183.666667
             58.0     58817.500000
             59.0    152303.000000
             60.0    163578.000000
Name: salary, Length: 278, dtype: float64

In [13]:
df.groupby(["Profession","Age","Marriage_proposal_count"]).salary.mean()

Profession   Age   Marriage_proposal_count
      Boxer  20.0  2                          119572.0
                   4                           35326.0
             23.0  3                           30976.0
             25.0  2                          162243.0
                   4                          103240.0
                                                ...
Teacher      57.0  2                          113363.0
             58.0  4                           83298.0
                   37                          34337.0
             59.0  1                          152303.0
             60.0  3                          163578.0
Name: salary, Length: 455, dtype: float64

In [15]:
# agg(): this function is used to apply multiple aggragate functions together

df[["Age","salary"]].agg(["mean","sum"])

               Age        salary
mean     40.810976  1.156028e+05
sum   20079.000000  5.780141e+07

In [17]:
# agg() : this  function is used to apply multiple aggregate functions together

df[["Age","salary"]].agg(["mean","sum","min","max"])

               Age        salary
mean     40.810976  1.156028e+05
sum   20079.000000  5.780141e+07
min      20.000000  3.016400e+04
max      60.000000  1.995290e+05

In [19]:
# apply different aggregate functions to different columns
df.agg({
    "Age" : ["min","mean"],
    "salary" : ["max","mean"]
})

            Age      salary
min   20.000000         NaN
mean  40.810976  115602.828
max         NaN  199529.000

In [21]:
# agg() + groupby()
df.groupby("Profession").agg({
    "Age" : ["min","mean"],
    "salary" : ["max","mean"]
})

                    Age             salary
                    min       mean     max           mean
Profession
      Boxer        20.0  39.547170  199529  103895.867925
Artist             20.0  36.736842  197685  124550.756098
Chef               20.0  43.344828  196494  110806.620690
Comedian           20.0  40.038462  198847  122689.000000
Detective          20.0  41.477273  194971  120964.977778
Doctor             22.0  43.152174  198978  113964.333333
Pilot              20.0  39.711538  199317  108641.471698
Scientist          22.0  41.000000  198095  126669.481481
Software Engineer  21.0  41.120000  198285  117908.941176
Teacher            20.0  41.022222  186127  107922.711111

# Merging of dataframes

In [29]:
# merge(): this function can be used to merge the dataframes based upon common column
# merge(): function work like join in sql : inner, left, right outer

df1 = pd.DataFrame({"ID" : [1,2,3],"Dream_company" : ["google","microsoft","Apple"]})
df2 = pd.DataFrame({"ID" : [2,3,4], "Dream_Package" : [10,15,18]})


#inner Join
merge_df = pd.merge(df1,df2, on = "ID")
merge_df


#outer Join

   ID Dream_company  Dream_Package
0   2     microsoft             10
1   3         Apple             15

In [35]:
#left join
merge_df = pd.merge(df1,df2, on = "ID", how = "left")
merge_df

   ID Dream_company  Dream_Package
0   1        google            NaN
1   2     microsoft           10.0
2   3         Apple           15.0

In [37]:
merge_df = pd.merge(df1,df2,on= "ID", how = "right")
merge_df

   ID Dream_company  Dream_Package
0   2     microsoft             10
1   3         Apple             15
2   4           NaN             18

In [39]:
merge_df = pd.merge(df1,df2,on= "ID", how = "outer")
merge_df

   ID Dream_company  Dream_Package
0   1        google            NaN
1   2     microsoft           10.0
2   3         Apple           15.0
3   4           NaN           18.0

# Join() : Mainly used to work with index

In [42]:
df3 = pd.DataFrame({"Hero_Name": ["NTR","Prabhas","Pawan"]}, index = [1,2,3])
df4 = pd.DataFrame({"Heroine_Name": ["Kajol","Anushkha","Shurti"]}, index = [2,3,4])
joined_df = df3.join(df4, how = "inner")
joined_df

  Hero_Name Heroine_Name
2   Prabhas        Kajol
3     Pawan     Anushkha

In [44]:
joined_df = df3.join(df4, how="outer")
joined_df

  Hero_Name Heroine_Name
1       NTR          NaN
2   Prabhas        Kajol
3     Pawan     Anushkha
4       NaN       Shurti

# concat

In [47]:
# Def : concat() function is used to stack dataframes vertically or horizontally

In [57]:
df5 = pd.DataFrame({"ID": [1,2],"Fav_Movie" : ["Paradise","Bahuballi"]})
df6 = pd.DataFrame({"ID" : [3,4], "Fav_Movie" : ["Spiderman","Doomsday"]})
df7 = pd.DataFrame({"ID": [5,6], "Fav_Movie": ["Pushpa","Maghadeera"]})


# axis = 0 : Veritically (adding rows)
# axis = 1 : Horizontally (adding columns)
concat_df = pd.concat([df5,df6], axis = 0, ignore_index = True)
concat_df

   ID  Fav_Movie
0   1   Paradise
1   2  Bahuballi
2   3  Spiderman
3   4   Doomsday

In [59]:
concat_df = pd.concat([df5,df6], axis = 1, ignore_index = True)
concat_df

   0          1  2          3
0  1   Paradise  3  Spiderman
1  2  Bahuballi  4   Doomsday

In [62]:
concat_df = pd.concat([df5,df6, df7], axis = 0, ignore_index = True)
concat_df

   ID   Fav_Movie
0   1    Paradise
1   2   Bahuballi
2   3   Spiderman
3   4    Doomsday
4   5      Pushpa
5   6  Maghadeera

In [64]:
concat_df = pd.concat([df5,df6,df7], axis = 1, ignore_index = True)
concat_df

   0          1  2          3  4           5
0  1   Paradise  3  Spiderman  5      Pushpa
1  2  Bahuballi  4   Doomsday  6  Maghadeera

# Times series based dataframe

In [69]:
# data_range() pandas function is used for generating date related data
data_rng = pd.date_range(start = "2020-01-01", end= "2026-12-31",freq = "YE")
data_rng

DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31',
               '2024-12-31', '2025-12-31', '2026-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

In [71]:
data_rng = pd.date_range(start = "2020-01-01", end= "2026-12-31",freq = "YS")
data_rng

DatetimeIndex(['2020-01-01', '2021-01-01', '2022-01-01', '2023-01-01',
               '2024-01-01', '2025-01-01', '2026-01-01'],
              dtype='datetime64[ns]', freq='YS-JAN')

In [73]:
data_rng = pd.date_range(start = "2020-01-01", end= "2026-12-31",freq = "MS")
data_rng

DatetimeIndex(['2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01',
               '2020-05-01', '2020-06-01', '2020-07-01', '2020-08-01',
               '2020-09-01', '2020-10-01', '2020-11-01', '2020-12-01',
               '2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01',
               '2021-05-01', '2021-06-01', '2021-07-01', '2021-08-01',
               '2021-09-01', '2021-10-01', '2021-11-01', '2021-12-01',
               '2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01',
               '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01',
               '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01',
               '2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01', '2023-11-01', '2023-12-01',
               '2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01',
               '2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01',
               '2025-09-01', '2025-10-01', '2025-11-01', '2025-12-01',
               '2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01',
               '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01',
               '2026-09-01', '2026-10-01', '2026-11-01', '2026-12-01'],
              dtype='datetime64[ns]', freq='MS')

In [75]:
data_rng = pd.date_range(start = "2020-01-01", end= "2026-12-31",freq = "ME")
data_rng

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31',
               '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31',
               '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31',
               '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31',
               '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31',
               '2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [79]:
data_rng = pd.date_range(start = "2020-01-01", end= "2026-12-31",freq = "d")
data_rng

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2026-12-22', '2026-12-23', '2026-12-24', '2026-12-25',
               '2026-12-26', '2026-12-27', '2026-12-28', '2026-12-29',
               '2026-12-30', '2026-12-31'],
              dtype='datetime64[ns]', length=2557, freq='D')

In [81]:
data_rng = pd.date_range(start = "2020-01-01", end= "2026-12-31",freq = "h")
data_rng

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 01:00:00',
               '2020-01-01 02:00:00', '2020-01-01 03:00:00',
               '2020-01-01 04:00:00', '2020-01-01 05:00:00',
               '2020-01-01 06:00:00', '2020-01-01 07:00:00',
               '2020-01-01 08:00:00', '2020-01-01 09:00:00',
               ...
               '2026-12-30 15:00:00', '2026-12-30 16:00:00',
               '2026-12-30 17:00:00', '2026-12-30 18:00:00',
               '2026-12-30 19:00:00', '2026-12-30 20:00:00',
               '2026-12-30 21:00:00', '2026-12-30 22:00:00',
               '2026-12-30 23:00:00', '2026-12-31 00:00:00'],
              dtype='datetime64[ns]', length=61345, freq='h')